services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Socialservices\:
    resource: '../Classes/*'

  JWeiland\Socialservices\EventListener\AllowSearchParameterEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Socialservices\Event\PreProcessControllerActionEvent

  JWeiland\Socialservices\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Socialservices\Event\PostProcessFluidVariablesEvent

  JWeiland\Socialservices\EventListener\AddGlossaryEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Socialservices\Event\PostProcessFluidVariablesEvent
      after: JWeiland\Socialservices\EventListener\AddPaginatorEventListener
